---
title: "Falkor standard visualization"
author: "William Kumler"
output: html_document
---
Add some more documentation! Why have you chosen to split the R chunks were you did? What is your function doing?
What should be produced by this?
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.table)

pmppm <- function(mass, ppm=4){
  if(mass<200){
    as.numeric(mass)+(c(-ppm, ppm)*200/1000000)
  } else {
    c(mass*(1-ppm/1000000), mass*(1+ppm/1000000))
  }
}
all_stans <- read.csv("falkor_stans.csv") %>% 
  filter(polarity=="pos",
         !is.na(mix)) %>% # if you're doing multiple steps of the same dplyr operation, just combine them
  # into one for clarity and less code.
  arrange(as.numeric(mz), as.numeric(rt)) %>%
  mutate(mz=as.numeric(mz))
stan_MS1_data <- readRDS("stan_data.rds")
addiso_peaks <- read.csv("addiso_peaks.csv")
real_peaks <- read.csv("real_peaks.csv")
all_peaks <- real_peaks %>%
  select(feature, mz, rt, into, file_name, M_area) %>%
  rbind(addiso_peaks %>% select(feature, mz, rt, into, file_name, M_area)) %>%
  arrange("feature", "file_name")
all_features <- all_peaks %>%
  group_by(feature) %>%
  summarise(mzmed=median(mz), rtmed=median(rt), avgarea=mean(M_area))
stan_annotations <- read.csv("stan_assignments.csv")
```

```{r, echo=FALSE}
for(mz_i in as.numeric(unique(all_stans$mz))){
  possible_stans <- all_stans %>% 
    filter(mz%between%pmppm(mz_i))
  possible_stan_features <- all_features %>%
    filter(mzmed%between%pmppm(mz_i)) %>%
    arrange(rtmed)
  stan_features <- possible_stan_features %>%
    left_join(stan_annotations, by=c(feature="best_guess")) %>%
    filter(!is.na(compound_name))
  if(!nrow(possible_stan_features)){
    print(paste("No peaks found for", possible_stans$compound_name))
    next
  }
  eic <- stan_MS1_data[mz%between%pmppm(mz_i)&
                         rt>min(possible_stan_features$rtmed)-50&
                         rt<max(possible_stan_features$rtmed)+100]
  eic_zeroed <- split(eic, eic$fileid) %>%
    lapply(function(x){
      rbind(
        data.frame(rt=min(x$rt), mz=median(x$mz), int=0, fileid=unique(x$fileid)),
        x,
        data.frame(rt=max(x$rt), mz=median(x$mz), int=0, fileid=unique(x$fileid))
      )
    }) %>% 
    do.call(what = rbind) %>%
    mutate(fillcol=str_extract(fileid, "Blk|Smp|Std")) %>%
    filter(fillcol=="Std") %>%
    mutate(stdtype=str_extract(fileid, "Mix[1|2]|H2O"))
  gp <- ggplot() + 
    geom_polygon(data = eic_zeroed, aes(x=rt, y=int, fill=stdtype)) +
    geom_line(data = eic_zeroed, aes(x=rt, y=int, group=stdtype)) +
    scale_y_continuous(oob = scales::rescale_none, limits = c(0, max(eic_zeroed$int)/5)) +
    # Consider a custom y axis label. "int" is a bit vague. could also just do a full
    # "retention time" label on the x axis too while you're at it.
    facet_wrap(~fileid) +
    scale_fill_viridis_d(alpha = 0.7, option = "C") +
    ggtitle(label = paste(possible_stans$compound_name, collapse = ", ")) +
    theme_bw()
  print(gp)
  print("Standard info:")
  possible_stans %>%
    select(compound_name, formula, rt, mz, mix) %>%
    mutate(rt=round(rt*60, digits = 2)) %>%
    arrange(rt) %>%
    print()
  print("Peaks detected:")
  possible_stan_features %>%
    left_join(stan_annotations, by=c(feature="best_guess")) %>%
    select(mzmed, rtmed, avgarea, compound_name) %>% 
    mutate(compound_name=ifelse(is.na(compound_name), "Unknown", compound_name)) %>%
    print()
}
```
